# Generated by Django 3.0.7 on 2020-07-01 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('address1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Street address')),
                ('address2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address 2')),
                ('locality', models.CharField(blank=True, max_length=50, null=True, verbose_name='City/Town')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='State/Province/County')),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zip/Postal code')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
