# Generated by Django 3.0.7 on 2020-07-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('view_profile', 'Can view profile'),)},
        ),
    ]
